### ISSUE TITLE
Still seeing ads in Blazer

### ISSUE THREAD

**Issue by j-hernandez** [xem/reverse-anti-anti-adblock-blocker-killer#2]
Please advise

Posted from my Palm Treo

**Comment by xem** [comment]
That's the intended behavior: this add-on's goal is to make ads non-invisible. Or the opposite, I'm never sure. :)

**Comment by j-hernandez** [comment]
Ok great! Closing. May open separate issues regarding:
- Tests?
- Back-button breaking
- Scrolling hi-jacked
